Juliet C# upgrade to net6.0 version!
flawgarden/JulietCSharp-mutated pull request #1
Opened 2024-06-21 08:53 UTC by DanielELog

I have yet to skim through the projects myself and verify the logic is kept intact. Nevertheless, it is up for grabs and discussion!

2024-06-21 09:14 UTC, misonijnik commented
Wow, what a fantastic piece of work! It looks awesome to me. Thank you!

To make it even better, could you add some simple CI to check the build on .NET 6.0?

I will review your PR after I get the build checked.

Thanks again!

2024-06-24 18:16 UTC, DanielELog commented
Hello there!

Added basic CI and tested it on my forked repo - you can inspect the run here: https://github.com/DanielELog/JulietCSharp-mutated/actions/runs/9650216146/job/26615384183?pr=1

2024-06-25 21:23 UTC, misonijnik requested changes

2024-06-25 21:23 UTC, misonijnik commented on README.md
> +# JulietC# mutated
JulietC# -> Juliet C#

2024-06-25 21:23 UTC, misonijnik commented on README.md
> +**JulietC# mutated** is aimed to create an extensive C# Benchmark for SAST tool evaluation. It is based on <a href="https://samate.nist.gov/SARD/test-suites/110">Juliet C# 1.3</a> and is currently un
JulietC# -> Juliet C#

2024-06-25 21:23 UTC, misonijnik commented on src/TestCaseSupport/TestCaseSupport/.updated
Is it necessary to have `.updated` files?

2024-06-25 21:23 UTC, misonijnik commented on .gitignore
Ignore only those paths related to the repository.

2024-06-25 21:28 UTC, misonijnik commented on README.md
> +**JulietC# mutated** is aimed to create an extensive C# Benchmark for SAST tool evaluation. It is based on <a href="https://samate.nist.gov/SARD/test-suites/110">Juliet C# 1.3</a> and is currently un
"is aimed" -> "aims"

2024-06-26 06:21 UTC, DanielELog commented on src/TestCaseSupport/TestCaseSupport/.updated
The upgrading script is not able to differentiate between old and new versions of each single project without them. They can be left out, but then if the script is ever called again, it will be confused.

2024-06-26 06:23 UTC, DanielELog commented on .gitignore
Could you please explain what paths you meant?

2024-06-26 13:43 UTC, misonijnik approved these changes

2024-06-26 13:44 UTC, merged